# Makefile
NAME = ex00

CC = c++

SRCS = main.cpp Bureaucrat.cpp


# Define the colors
RED=\033[0;31m
GREEN=\033[1;32m
YELLOW=\033[1;33m
NC=\033[0m #color reset value (No color)

all: $(NAME)
		$(CC) $(SRCS)

$(NAME):
		@echo "$(GREEN)Compiling ex00 with MakeFile...$(NC)"
		$(CC) $(SRCS)